spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Mypassword2017
    url: jdbc:mysql://594557ca0821e.sh.cdb.myqcloud.com:8458/springcloud_sell?characterEncoding=utf-8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
