spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Mypassword2017
    url: jdbc:mysql://594557ca0821e.sh.cdb.myqcloud.com:8458/springcloud_sell?characterEncoding=utf-8
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
env:
  test8
